a = input('Digite algo ')
print('O tipo primitivo desse valor é:', type(a))
print('Só tem espaço?', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alabetico? ', a.isalpha())
print('É alfanumerico? ', a.isalnum())
print('Está em maiusculas?', a.isupper())
print('Está em minusulas?', a.islower())
print('Está capitalizada?', a.istitle())

